spring.datasource.url=jdbc:mysql://localhost:3307/basicmapping
spring.datasource.username=user
spring.datasource.password=password
spring.kafka.bootstrap-servers=localhost:9092
spring.jpa.hibernate.ddl-auto=update